version: 2

jobs:
  deploy:
    docker:
      - image: circleci/python:3.5
    working_directory: ~/k6-js-lib
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/k6-js-lib
          paths:
            - deploy.sh
      - attach_workspace:
          at: ~/k6-js-lib
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Deploy lib to s3
          command: ~/k6-js-lib/deploy.sh

workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
